name: Automated Tests

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  # schedule:
  #   - cron: '42 22 * * *'
  push:
    # branches: [ "main" ]
    # # Publish semver tags as releases.
    # tags: [ 'v*.*.*' ]
  pull_request:
    # branches: [ "main" ]
  workflow_dispatch: 
  repository_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup test environment
        run: |
          pip install -U pip
          pip install -U -r src/requirements.txt
          pip install -U pytest

      - name: Run tests
        run: pytest -v

